name: carlog
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.3
  image_picker: ^1.1.2
  firebase_core: ^3.11.0
  flutter_debouncer: ^2.0.0
  http: ^1.3.0
  image: ^4.5.3
  flutter_dotenv: ^5.2.1
  flutter_image_compress: ^2.4.0
  firebase_auth: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
